baseURL = "https://maanuj-vora.github.io/"
languageCode = "en-us"
title = "Coders' Haven"
enableGitInfo = true
publishDir = "public"
theme = "book"
[params]
    BookTheme = 'auto'
    BookMenuBundle = 'menu'
    BookSection = 'docs'
    BookSearch = true
    BookComments = false