baseURL = "https://maanuj-vora.github.io/Coders-Haven/"
languageCode = "en-us"
title = "Coders' Haven"
theme = "book"
enableGitInfo = true

[params]
    BookTheme = 'auto'
    BookMenuBundle = 'menu'
    BookSection = 'docs'
    BookSearch = true
    BookComments = false
    BookRepo = 'https://github.com/Maanuj-Vora/Coders-Haven'
    BookEditPath = 'edit/master/content'
    
