name: Contributing to the Contributors

on: [push]

jobs:
  build:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Maanuj-Vora/List-Contributors@0.0.2
        with:
          REPO_NAME: '${{github.repository}}'
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CONTRIBUTOR: '### Contributors'
          ENDCONTRIBUTOR: '---'
          FILEPATH: '/content/contributor/_index.md'
          COLUMN_PER_ROW: '4'
          IMG_WIDTH: '50'
          FONT_SIZE: '14'
          COMMIT_MESSAGE: 'Contributed to Contributor List'
