name: Floor Moderator

on: [push, issues]

jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        name: Looking Around
        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@master
              with:
                  readme_path: "content/contributors/_index.md"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
