name: Floor Moderator

on: 
  schedule:
    - cron: "0 0 * * 0"

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BobAnkh/add-contributors@master
      with:
        REPO_NAME: 'Maanuj-Vora/Coders-Haven'
        CONTRIBUTOR: '# Contributors'
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: 'content/contributors/_index.md'
        COMMIT_MESSAGE: 'Looking around'
        AVATAR_SHAPE: 'round'
