name: Floppy Disk or Save Icon

on:
  [push]
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - "content/**"

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10.x]

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.75.1"
          extended: true

      - name: Configure commiter
        run: |
          git config --local user.email "buddy@bracketspace.com"
          git config --local user.name "Hard Worker"

      - name: Gimme the perms
        run: chmod +x ./scripts/publishScript.sh

      - name: Do your worst
        run: |
          sh ./scripts/publishScript.sh

      # - name: Committing
      #   run: |
      #     git add public
      #     git commit -m "I am in charge 🗡️" -a
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
